### ISSUE TITLE
Proposal: Add executable

### ISSUE THREAD

**Issue by chazanov** [mkly/youtube-closed-captions#4]
What about adding a wrapper to the library, e.g. /usr/bin/ytcc ?

**Comment by mkly** [comment]
Hello! I never really thought of this. Mostly my use case has been for pulling in captions in python. And this makes it fairly simple for me. My thought is that because this is is based upon [youtube-dl](http://ytdl-org.github.io/youtube-dl/) you could likely just use that instead https://github.com/ytdl-org/youtube-dl/blob/master/README.md#subtitle-options

I feel like most people who use this are more data science focused and this is an easier way for them to pull into video data in something like a Jupyter notebook.

**Comment by chazanov** [comment]
Ain't a commandline tool 10x easier than a fancy Jupyter notebook? I slowly realize than I've become a computing fossil ;)

**Comment by mkly** [comment]
My appologies for not being a bit more clear with my earlier comment. You can already use [youtube-dl](http://ytdl-org.github.io/youtube-dl/) to download captions(subtitles). Try this:

`youtube-dl --write-sub --skip-download https://www.youtube.com/watch\?v\=jNQXAC9IVRw`

Let me know if that helps.
